max_steps: 1000
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 2e-4
warmup_ratio: 0.03
logging_steps: 10
eval_strategy: steps
eval_steps: 100
save_steps: 200
bf16: true
